version: "3.8"
services:
  redis_DB:
    image: redis:latest
    container_name: redis_for_weather_api
    ports:
      - "6379:6379" 
    volumes:
       - weather_api_data:/data # Монтирование volume для сохранения данных

volumes:
    weather_api_data: